-----1) Create the necessary data structures to contain the data specified in the Appendix ensuring that data integrity is enforced

CREATE TABLE DEPARTMENT 
(
DEPARTMENT_ID   NUMBER(5) PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(50),
LOACTION        VARCHAR2(50)
);


CREATE TABLE EMPLOYEE
(
EMPLOYEE_ID NUMBER(10) PRIMARY KEY,
EMPLOYEE_NAME VARCHAR2(50) ,
JOB_TITLE VARCHAR2(50),
MANAGER_ID NUMBER(10),
DATE_HIRED DATE,
SALARY NUMBER(10),
DEPARTMENT_ID NUMBER(5),
FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

