------7) Write a report to show all Employees for a Department



SELECT E.DEPARTMENT_ID,D.DEPARTMENT_NAME,E.EMPLOYEE_NAME,E.EMPLOYYE_ID FROM EMPLOYEE E ,DEPARTMENT D WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID  AND D.DEPARTMENT_ID=2 GROUP BY E.DEPARTMENT_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME,E.EMPLOYYE_ID ORDER BY 1 ;--LIST OF ALL EMPLOYEES assuming ENGINEERING DEPARTMENT


SELECT E.DEPARTMENT_ID,D.DEPARTMENT_NAME,E.EMPLOYEE_NAME,E.EMPLOYEE_ID FROM EMPLOYEE E ,DEPARTMENT D WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID GROUP BY E.DEPARTMENT_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME,E.EMPLOYEE_ID ORDER BY 1 ;--LIST OF ALL EMPLOYEES BASED ON  DEPARTEMNTS 
