------8)Write a report to show the total of Employee Salary for a Department

SELECT E.DEPARTMENT_ID,D.DEPARTMENT_NAME,SUM(E.SALARY) TOTAL_EMP_SAL FROM EMPLOYEE E ,DEPARTMENT D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID GROUP BY E.DEPARTMENT_ID,D.DEPARTMENT_NAME HAVING COUNT(e.employye_id)>=1 ORDER BY 1 ;
