
-----3)Create an appropriate executable database object to allow an Employee to be created

create or replace PROCEDURE NEW_employee(
      P_EMPLOYEE_ID NUMBER,
      P_EMPLOYEE_NAME VARCHAR2,
      P_JOB_TITLE VARCHAR2,
      P_MANAGER_ID NUMBER,
      P_DATE_HIRED DATE,
      P_SALARY NUMBER,
      P_DEPARTMENT_ID NUMBER
) IS
    BEGIN    

    INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, JOB_TITLE, MANAGER_ID, DATE_HIRED, SALARY, DEPARTMENT_ID) 
    VALUES(P_EMPLOYEE_ID, P_EMPLOYEE_NAME, P_JOB_TITLE, P_MANAGER_ID, P_DATE_HIRED, P_SALARY, P_DEPARTMENT_ID);
 
EXCEPTION 
     WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Duplicate value on an EMPLOYEE_ID');
END;
/
