----4)Create an appropriate executable database object to allow the Salary for an Employee to be increased or decreased by a percentage

create or replace PROCEDURE INC_OR_DEC_SALARY(
      P_EMPLOYEE_ID NUMBER,
      P_STATUS VARCHAR2,
      P_PERCENTAGE NUMBER
) AS
     A_STATUS VARCHAR2(10);
     A_PERCENTAGE NUMBER;
     A_SALARY  NUMBER;
     V_SALARY NUMBER;
BEGIN

      A_STATUS:=P_STATUS;
      A_PERCENTAGE:=P_PERCENTAGE;

  SELECT SALARY INTO V_SALARY FROM EMPLOYEE WHERE EMPLOYEE_ID=P_EMPLOYEE_ID;

  IF upper(trim(A_STATUS)) = 'good'
  THEN
  A_SALARY:=V_SALARY+(V_SALARY*A_PERCENTAGE/100);
    UPDATE  Employee SET SALARY =A_SALARY WHERE EMPLOYEE_ID=P_EMPLOYEE_ID;
  ELSIF A_STATUS='bad'
  then
  A_SALARY:=V_SALARY-(V_SALARY*A_PERCENTAGE/100);
    UPDATE  Employee SET SALARY =A_SALARY WHERE EMPLOYEE_ID=P_EMPLOYEE_ID; 
  END IF;
  
  EXCEPTION
   WHEN no_data_found then
   DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID ENTERED IS NOT CORRECT');
   WHEN OTHERS THEN 
   DBMS_OUTPUT.PUT_LINE('OTHERS'); 
  
END;
/